### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/littleFACt#47]
https://github.com/FAC-11/littleFACt/blob/master/tests/test.js#L22-L27

The above test is a little over-complicated. You should try to keep `expected` as simple as possible. The functionality would stay the same with expected as `-1` (instead of calling String.indexOf(' ')).

https://github.com/FAC-11/littleFACt/blob/master/tests/test.js#L28-L33

The same is true with this test. You could even just remove the indexOf's altogether like the test below

**Comment by rachaelcodes** [comment]
Just wanted to add (in the tests conversation) that I really like how precise you've been with your tests testing different things.

It's particularly clear how you've used your tests to check how you've refined your destStr function to make your site work for loads of different cases. ❤️
